#cloud-config
package_update: true
package_upgrade: true

packages:
  - network-manager

hostname: dhcp-client
disable_root: false
ssh_pwauth: true
chpasswd:
  list: |
    onyo:password
    root:password
  expire: false
users:
  - name: onyo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false

power_state:
  mode: reboot
  message: "Init complete. Rebooting."
  timeout: 10
  condition: true